schemaVersion: 2.2.0
metadata:
  name: k8s-sample
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 1G
      memoryLimit: 4G
      cpuRequest: '1'
      cpuLimit: '2'
      env:
        - name: OPENVSX_REGISTRY_URL
          value: ''

commands:
  - id: install-dependencies
    exec:
      label: 1. Install dependencies
      component: tools
      commandLine: npm install
  - id: compile
    exec:
      label: 2. Compile an Run
      component: tools
      commandLine: npm run compile && node ./out/main.js
      group:
        kind: build
        isDefault: true
  - id: patch-product-json
    exec:
      # put your tooling container name here
      component: tools
      commandLine: |
        // patch product.json
        jq '.extensionsGallery += {"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery"}' /checode/checode-linux-libc/ubi8/product.json > /checode/checode-linux-libc/ubi8/product.copy.json
        mv -f /checode/checode-linux-libc/ubi8/product.copy.json /checode/checode-linux-libc/ubi8/product.json
        jq '.extensionsGallery += {"itemUrl": "https://marketplace.visualstudio.com/items"}' /checode/checode-linux-libc/ubi8/product.json > /checode/checode-linux-libc/ubi8/product.copy.json
        mv -f /checode/checode-linux-libc/ubi8/product.copy.json /checode/checode-linux-libc/ubi8/product.json
        jq '.extensionsGallery += {"cacheUrl": "https://vscode.blob.core.windows.net/gallery/index"}' /checode/checode-linux-libc/ubi8/product.json > /checode/checode-linux-libc/ubi8/product.copy.json
        mv -f /checode/checode-linux-libc/ubi8/product.copy.json /checode/checode-linux-libc/ubi8/product.json
        // reset launcher script to avoid losing the settings
        echo "export class OpenVSIXRegistry { async configure() {} }" > /checode/checode-linux-libc/ubi8/launcher/openvsix-registry.js

events:
  postStart:
    - patch-product-json
