schemaVersion: 2.2.0
metadata:
  name: k8s-sample
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryRequest: 1G
      memoryLimit: 4G
      cpuRequest: '1'
      cpuLimit: '2'

commands:
  - id: install-dependencies
    exec:
      label: 1. Install dependencies
      component: tools
      commandLine: npm install
  - id: compile
    exec:
      label: 2. Compile an Run
      component: tools
      commandLine: npm run compile && node ./out/main.js
      group:
        kind: build
        isDefault: true
